### ISSUE TITLE
Rewrite More Features structure

### ISSUE THREAD

**Issue by nbarbettini** [nbarbettini/little-aspnetcore-book#13]
Currently the Add more features chapter tells you to use jQuery to make AJAX calls to some pseudo-API controllers. It would be better to stay fully inside the MVC fold and then contrast with a SPA architecture, instead of mixing metaphors.

**Tl;dr** - more MVC, less jQuery.

**Comment by welkie** [comment]
Many people consider MPAs (multi-page applications) with AJAX for a few features to be a good alternative to SPAs when you don't need (or can't allow) everything to live in the browser. Showing how to implement a few controller actions to do this probably deserves mention in a "more features" section. However, I agree that it shouldn't be mixed with the core stuff. Perhaps both AJAXifying and doing an SPA both deserve their own sections in multiple "more features" type sections.

**Comment by nbarbettini** [comment]
> Perhaps both AJAXifying and doing an SPA both deserve their own sections in multiple "more features" type sections.

I definitely went back and forth on this while writing the initial version. It feels like Razor, AJAX, and full-blown SPA could each deserve their own fork of the book. 😄

**Comment by welkie** [comment]
Funny you mention that. Another thing I was thinking about was this:

This book is tiny. It doesn't expand on many non-MVC features. It's only what you need to get things running basically. And I love that. I think that to try to expand this book to include everything every developer reading it can think of would ruin that experience. It does only one thing, but it does it really well, and I'd like to see it stay that way.

Perhaps it would be worth creating more books which continue the tutorial completed in the book with their own themes. We could have:

- The Little ASP.NET Core AJAX Book (Start from the finished tutorial in the original book, and add AJAX features)
- The Little ASP.NET Core SPA Book (Start from the finished tutorial in the original book, and convert it to an SPA with whichever set of RESTful routes etc would be needed)

The community would have an opportunity to explore these other ideas without ruining the quick and effective style of the original book.

**Comment by nbarbettini** [comment]
Yep, that's exactly what I was thinking. I really like the size and scope of this little book. The Little ASP.NET Core Book could be a great starting point for:

* The Little ASP.NET Core REST API Book
* The Little ASP.NET Core + Angular Book
* The Little ASP.NET Core + React Book
* (A Little More) Advanced ASP.NET Core MVC

The "only" thing that needs to be done is write them.

**Comment by sadqiang** [comment]
It is much better if "Add More Features" section discusses CRUD operations that are usually generated by scaffolding including HttpPost and HttpGet attributes.

**Comment by nbarbettini** [comment]
@sadqiang I agree. In the next update I'm going to rewrite this section and get rid of the AJAX stuff.

**Comment by nbarbettini** [comment]
Resolved via d1a208638f1e734ec6bef65172bf1e466ad9cf19
