### ISSUE TITLE
Extend "Use a database" chapter with existing database info

### ISSUE THREAD

**Issue by duke1102** [nbarbettini/little-aspnetcore-book#16]
Hey.

I think it would benefit the "**Database**" chapter a lot, if you talk about what to understand under the terms "**Code First**" and "**Database First**" and how to actually use EF to automatically create Models and DbContext from pre-existing database tables.  
I'd assume that a bunch of people already have some sort of database structure set up which they would like to use later, even if it's not really needed for the tutorial project.

**Comment by nbarbettini** [comment]
The EF team seems to be moving away from "code first" and "database first". The [new EF Core docs](https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/existing-db) just refer to "existing database".

I don't want to get the reader too off-track from the tutorial. Maybe just a note that you can use `Scaffold-DbContext` if you have an existing database?

**Comment by duke1102** [comment]
Oh, okay, didn't notice that.

But I agree, just a small paragraph at the end of the chapter that hints about this with an short example will totally suffice!

**Comment by nbarbettini** [comment]
Added. Let me know what you think @duke1102!

**Comment by duke1102** [comment]
Hey! Yea, looks sufficient enough!
I'm hoping to get back to translating the book to German soon, haven't really had the time lately.

**Comment by nbarbettini** [comment]
Sounds good! Let me know if you finish translating the book, I'll be happy to promo it here!
