### ISSUE TITLE
Unit test error in AddItemAsync

### ISSUE THREAD

**Issue by nbarbettini** [nbarbettini/little-aspnetcore-book#22]
Feedback:

> When running Unit tests: there is an error in test execution, but the test project doesn’t say anything more than this generic error message. (I tried in both VS Code and VS 2017 15.4)
Message: System.NullReferenceException : Object reference not set to an instance of an object.
 
> I tracked it down to the second parameter of the AddItemAsync method, which expects a user but is getting passed a null value from the test method.

**Comment by GarethOates** [comment]
This wasn't mentioned in the book but before I could get the UnitTest to run I had to do the following:

`dotnet add package Microsoft.EntityFrameworkCore`

Should I raise a separate issue for this or do you think it could be related to your current issue?

**Comment by windsting** [comment]
Yes, this is an error, I got a comment on this page:
https://windsting.github.io/little-aspnetcore-book/book/chapters/automated-testing/unit-testing.html

I checked the code it seems caused by the `null` in this line:

    await service.AddItemAsync(new NewTodoItem { Title = "Testing?" }, null);

**Comment by nbarbettini** [comment]
Fixed in https://github.com/nbarbettini/little-aspnetcore-book/commit/fbddcaedbb7715d6a1df5f7a48ddd425393ea10b
