### ISSUE TITLE
The Chinese version has another translator

### ISSUE THREAD

**Issue by windsting** [nbarbettini/little-aspnetcore-book#33]
Sorry for my fault, I forgot to tell you that the Chinese version was translated by me and a colleague, I've put his name(`yuyi`) in the **Conclusion** page:

https://windsting.github.io/little-aspnetcore-book/book/chapters/conclusion/#特别致谢

Would you please add his name on your page? Thank you in advance.

**Comment by nbarbettini** [comment]
Does this look good?

* windsting, yuyi (Simplified Chinese)

**Comment by windsting** [comment]
👌 yes, that will be good, thank you.

**Comment by nbarbettini** [comment]
Done: https://github.com/nbarbettini/little-aspnetcore-book/commit/83f2998961253cd08a3e72dbc8c546efa50ba271

Thank you both for your work!
