### ISSUE TITLE
Taking a project that allows registered users to do CRUD on authorized parts of their own and others

### ISSUE THREAD

**Issue by sadqiang** [nbarbettini/little-aspnetcore-book#36]
Most of us probably know stackoverlow.com and its variants. A user allows to submit questions, answers and comments to their own and others.

The current project developed in this book does not teach us how to allow registered users to do such CRUD mentioned above.  Taking a stackoverflow.com-like project as a tutorial seems to be more interesting as it covers the missing important parts about integrating Question, Answer, Comment entity model with the identity model.

**Comment by welkie** [comment]
I agree that a more advanced tutorial including limiting access to resources with auth features (claims, object ownership, etc) would be great. I wonder if @nbarbettini would consider adding a second project to the book for people to complete after they complete the first?

**Comment by nbarbettini** [comment]
This is covered very briefly in [Using identity in the application](https://github.com/nbarbettini/little-aspnetcore-book/blob/master/chapters/security-and-identity/using-identity-in-the-application.md).

The idea of a second project is intriguing. I think it would be outside the scope of this book. A book covering more advanced application development with ASP.NET Core would be cool, but a ton of work to write.

**Comment by nbarbettini** [comment]
Closing this as it's outside the scope of this book.

No announcements at the moment, but I'd definitely like to write an "advanced topics" book in the future. Thanks for the suggestion.
