### ISSUE TITLE
AddItemAsync

### ISSUE THREAD

**Issue by sahinyanlik** [nbarbettini/little-aspnetcore-book#4]
In this page "https://nbarbettini.gitbooks.io/little-asp-net-core-book/content/chapters/add-more-features/add-todo-items.html#" you are calling  await _todoItemService.AddItemAsync(newItem); but in TodoItemService your methodd name is different "public async Task<bool> AddItem(NewTodoItem newItem)"

**Comment by nbarbettini** [comment]
That's a typo, thanks!
