### ISSUE TITLE
Why don't we use AddDbContextPool instead of AddDbContext?

### ISSUE THREAD

**Issue by sadqiang** [nbarbettini/little-aspnetcore-book#48]
[New features in EF Core 2.0](https://docs.microsoft.com/en-us/ef/core/what-is-new/) explains there is `AddDbContextPool` for gaining high performance. Why don't we use it?

**Comment by nbarbettini** [comment]
Looks like a really cool feature!

> Why don't we use it?

It's out of scope for this simple project. This book doesn't try to teach readers everything about EF Core. There are dedicated EF Core books just for that (if not, you should write one! 😄). The goal of this book is to get the reader interested in learning more.
