### ISSUE TITLE
Explain nullable type in create-models.md (DateTimeOffset?)

### ISSUE THREAD

**Issue by Chaz6** [nbarbettini/little-aspnetcore-book#5]
It would be useful to inform the reader that "?" indicates that the type is nullable.

**Comment by saint4eva** [comment]
The author assumes that the reader ought to have  basic knowledge of C#. Notwithstanding, some pieces of code should be explained...

**Comment by welkie** [comment]
I disagree with that. In the intro, it says:

> If you're new to programming, this book will introduce you to the patterns and concepts used to build modern web applications. You'll learn how to build a web app (and how the big pieces fit together) by building something from scratch! While this little book won't be able to cover absolutely everything you need to know about programming, it'll give you a starting point so you can learn more advanced topics.+
> 
> If you already code in a backend language like Node, Python, Ruby, Go, or Java, you'll notice a lot of familiar ideas like MVC, view templates, and dependency injection. The code will be in C#, but it won't look too different from what you already know.

This sounds like the book is also ideal for those who are new to programming, which would include people who have never used a programming language with nullable types the way C# uses them, and who may not yet be familiar enough with C# to have learned about nullable types. I think it's worth a quick explanation in the book.

**Comment by nbarbettini** [comment]
I added some explanation in https://github.com/nbarbettini/little-aspnetcore-book/commit/01bb68af9802905f8426f07055acce9f0eafe0db. @welkie what do you think?

**Comment by welkie** [comment]
Sorry for replying late, busy with school. @nbarbettini looks great!
