### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by jphellemons** [nbarbettini/little-aspnetcore-book#57]
Hi, it's probably because stuff changed on the side of FB, but the screenshot on page 72 is not accurate anymore, and when clicking on the login button I get this (dutch, sorry) message:

<img width="258" alt="fb-login" src="https://user-images.githubusercontent.com/1119134/39753909-b88769e0-52c0-11e8-8f7d-47bfd2353f13.PNG">

roughly translated it says: cannot load url, the domain of this url is not added to the domains of this app. add all domains and subdomains of the app in the field appdomains of the settings of your app to be able to load this url.

my app runs on port 5001 instead of the default 5000. Don't know why, but it's how it is. So I configured it like this:

<img width="472" alt="fb-settings" src="https://user-images.githubusercontent.com/1119134/39753970-ec747932-52c0-11e8-94b2-90e3e9a55c3a.PNG">

it's probably just a wrong field because of the FB Dev page change. So it could use new screenshots in the book :)

**Comment by nbarbettini** [comment]
You're right, the instructions drifted out of date after Facebook made some changes on their side. The newest version (download [here](http://littleasp.net/book)) removes the Facebook login section entirely so it's less confusing for first-timers.

I may add social login back again in the future (see #21).
