### ISSUE TITLE
Page 93: for technical reasons you cannot use await in Program.cs

### ISSUE THREAD

**Issue by jphellemons** [nbarbettini/little-aspnetcore-book#59]
or on the top of page 90 of the old version of the book.
Is it an idea to have a **short explanation** there? Or a reference? About why you can't await in program.cs I am just curious and this "for technical reasons" is a trigger for me to google it. But can't find a good/clear explanation.

**Comment by nbarbettini** [comment]
Here's the longer explanation: https://blogs.msdn.microsoft.com/mazhou/2017/05/30/c-7-series-part-2-async-main/

As mentioned in the above post, this will be changing soon (when C# 7.1 becomes the default). When that happens, I'll update the book to remove the note entirely.
