### ISSUE TITLE
Identity exception

### ISSUE THREAD

**Issue by jphellemons** [nbarbettini/little-aspnetcore-book#61]
<img width="664" alt="identity" src="https://user-images.githubusercontent.com/1119134/39814103-46854c4e-5393-11e8-92a0-b02ca5f8e62b.PNG">
I am running 2.1.300-preview2-008530 which might cause it.
So I have some small differences between the version used in the book and mine.
I have published what I have so far in this repo: https://github.com/jphellemons/LittleBook

for instance in program.cs `BuildWebHost` vs `CreateWebHostBuilder`
https://github.com/jphellemons/LittleBook/blob/fc5cbead616bed11dab832f72afa8638fe702869/LittleBook/Program.cs#L18

But I have missed something in the Startup.cs I think:
>InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser]' has been registered.

But I have the applicationuser and identityuser service here:
https://github.com/jphellemons/LittleBook/blob/fc5cbead616bed11dab832f72afa8638fe702869/LittleBook/Startup.cs#L42

I have checked the book and can't find my error. Did I really miss something? If it's not because of a small missing part of the book. Then I am sorry and I should have posted it on StackOverflow instead of filing an issue. I just want to give some feedback on the book to try and add value. So that the book even gets better and might help more people :) and to learn stuff myself.

**Comment by nbarbettini** [comment]
FYI, the book is not compatible with 2.1 yet. I haven't tried it myself, so I'm not sure yet if this is due to a 2.1 difference or not.

**Comment by jphellemons** [comment]
No problem, I was just checking if my error was due to the small differences between the versions of the book. I downloaded the old book version just days after you released the new version (without the FB auth and secrets). I will try to figure this one out myself and will update this when I have the solution so that it might help other people who have the same issue.

**Comment by jphellemons** [comment]
Let's close this issue, as it is probably similar to https://github.com/nbarbettini/little-aspnetcore-book/issues/65#issuecomment-396082913
