### ISSUE TITLE
Possible typo on page 94

### ISSUE THREAD

**Issue by MayhemMike** [nbarbettini/little-aspnetcore-book#64]
in the code for Views/Shared/_AdminActionsPartial.cshtml:

`@if (signInManager.IsSignedIn(User))
{
var currentUser = await UserManager.GetUserAsync(User);
var isAdmin = currentUser != null`

"UserManager.GetUserAsync" causes error CS0305:Using the generic type 'UserManager<TUser>' requires 1 type arguments"

I'm an asp noob so no idea but changing it to lower case "**u**serManager.GetUserAsync(User);"
seems to work

**Comment by nbarbettini** [comment]
What does your `@inject` line look like at the top of the file?

**Comment by nbarbettini** [comment]
Good catch - this was indeed a typo. @zhilich fixed it in #63 👍
