### ISSUE TITLE
Uncaught exception when using Humanizer

### ISSUE THREAD

**Issue by spokomaciek** [nbarbettini/little-aspnetcore-book#7]
In _Add external packages_ chapter, we start using Humanizer. I have encountered the following error:
`fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]`
`An unhandled exception has occurred: The resource object with key 'DateHumanize_Mul
tipleDaysFromNow' was not found`
`Parameter name: resourceKey`
I think it may be caused by the fact that my Windows and Chrome are in Polish. After changing `Humanizer.Core` to `Humanizer` everything started working. It would be good to add a little note about this.

**Comment by nbarbettini** [comment]
You're right, I should have referenced `Humanizer` instead of `Humanizer.Core`. Fixed!
