### ISSUE TITLE
Missing instructions for "deploying to IIS"?

### ISSUE THREAD

**Issue by RayDeanTech** [nbarbettini/little-aspnetcore-book#75]
I see a section for Azure and Docker, but I don't see the IIS instructions.

Are there any plans to write instructions on deploying an ASP.net Core 2.2 application to IIS?

(I'm having troubles finding a decent tutorial)

Thank you.

**Comment by nbarbettini** [comment]
No current plans to add an IIS section, since the book was written to be inclusive of non-Windows users wherever possible. I would review a PR though, if you are inclined!

**Comment by nbarbettini** [comment]
If you have access to LinkedIn Learning (formerly Lynda), I have a course on deploying ASP.NET Core apps available there: https://www.linkedin.com/learning/instructors/nate-barbettini

If you aren't a subscriber, shoot me an email and I can send you a coupon code. Cheers!
