### ISSUE TITLE
Update The Context Clarification

### ISSUE THREAD

**Issue by useless-sql** [nbarbettini/little-aspnetcore-book#76]
I'm very new to building an ASP.NET Core application, this book is a great hands on introduction.  However, as I work through the "Use a Database > Update the Context" section, the following statement is giving me an issue:

public class ApplicationDbContext 
             : IdentityDbContext<ApplicationUser>

In the code, there is no "ApplicationUser" type and throwing the error "The type or namespace could not be found."  Was this defined in a previous chapter, what am I missing?

**Comment by nbarbettini** [comment]
Hi @useless-sql - is the error on that line or somewhere else? It's possible some of the instructions in the book have become outdated. I haven't had time to update it recently.

**Comment by nbarbettini** [comment]
Ah, is yours the same issue as this? https://github.com/nbarbettini/little-aspnetcore-book/issues/70

**Comment by useless-sql** [comment]
Yes, I am working through the book.  It wasn't referenced there, but I see it in the example code.  I will use that as another reference going forward.

Thank you

**Comment by nbarbettini** [comment]
Glad that helped! Good luck with the rest of the book.

Sorry that parts of it may have drifted out of date. I plan to publish an updated revision when ASP.NET Core 3.0 is released.
