### ISSUE TITLE
Hi, Anyone is planning work into improve this book?

### ISSUE THREAD

**Issue by wkrea** [nbarbettini/little-aspnetcore-book#77]
I'm interested on join to this, to translate to spanish version. :)

Let me know please, how can i help? after of clone and translate?

**Comment by nbarbettini** [comment]
There was discussion of a Spanish translation here: https://github.com/nbarbettini/little-aspnetcore-book/issues/54
It looks like @jahbenjah finished the translation! I haven't had time to review, so I'm sure it would be helpful to review and offer any suggestions/improvements.

I'm planning to do some work to improve the English version, but don't have time right now.
